services:
  nginx:
    image: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  service1:
    image: service1
    container_name: tiras-service1
    build: 
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    networks:
      - webnet

  service2:
    image: service2
    container_name: tiras-service2
    build: 
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - "6005:6005"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge